In [2]:
df = spark.read.load('/data/citibike.parquet')
df = df.repartition(662, "start_station_id")
df = df.sortWithinPartitions("start_time")
# df.write.parquet('/data/citibike_partitioned.parquet', 
# #                  partitionBy=['start_station_id'], 
#                  mode='overwrite', compression="snappy")

Column<b'start_time'>

In [37]:
df1 = spark.sql('''SELECT start_station_id, std(start_station_latitude) as lat, 
                          std(start_station_longitude) as lon
                     from parquet.`/data/citibike.parquet`
                     group by start_station_id
                     order by start_station_id
                     ''')
df2 = spark.sql('''SELECT end_station_id, end_station_latitude, 
                          end_station_longitude
                     from parquet.`/data/citibike.parquet`''')

In [47]:
df1 = spark.sql('''SELECT start_station_id, count(start_station_id) as c
                     from parquet.`/data/citibike.parquet`
                     group by start_station_id
                     order by c asc
                     ''')

In [48]:
df1.show()

+----------------+---+
|start_station_id|  c|
+----------------+---+
|            3385|  1|
|            3240|  3|
|            3266|  7|
|            3036| 10|
|            3040| 11|
|            3017| 12|
|            3239| 18|
|            3252| 20|
|            3432| 24|
|            3250| 25|
|            3371| 53|
|            3253| 62|
|            3245|177|
|            3257|178|
|            3219|180|
|            3014|324|
|            3130|351|
|            3342|410|
|            3326|429|
|            3394|450|
+----------------+---+
only showing top 20 rows

In [61]:
spark.sql('''SELECT end_station_name, end_station_id, end_station_latitude, end_station_longitude
                     from parquet.`/data/citibike.parquet`
                     where end_station_name LIKE '%SSP%'
                     limit 100
                     ''').show()

+-------------------+--------------+--------------------+---------------------+
|   end_station_name|end_station_id|end_station_latitude|end_station_longitude|
+-------------------+--------------+--------------------+---------------------+
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
|"NYCBS Depot - SSP"|           255|           40.646767|            -74.01651|
+-------------------+--------------+--------------------+---------------------+
only showing top 20 rows

In [62]:
df1 = spark.sql('''SELECT end_station_id, first(end_station_name), count(end_station_id) as c
                     from parquet.`/data/citibike.parquet`
                     group by end_station_id
                     order by c asc
                     ''')
df1.toPandas()

     end_station_id     first(end_station_name, false)       c
0              3220                "5 Corners Library"       1
1              3196                   "Riverview Park"       1
2              3206                          "Hilltop"       1
3              3192               "Liberty Light Rail"       1
4              3197                         "North St"       1
5              3439  "Broadway & E 22 St - Valet Scan"       1
6              3212                  "Christ Hospital"       1
7              3247                   "SSP - Basement"       1
8              3191                         "Union St"       1
9              3198                 "Heights Elevator"       2
10             3276                 "Marin Light Rail"       2
11             3199                     "Newport Pkwy"       2
12             3267                     "Morris Canal"       2
13             3385                 "2 Ave & E 105 St"       2
14             3275                   "Columbus Drive"       2
15             3211                       "Newark Ave"       3
16             3039                "NYCBS Depot - DYR"       3
17             3202                     "Newport PATH"       3
18             3187                        "Warren St"       3
19             3225            "Baldwin at Montgomery"       3
20             3185                        "City Hall"       4
21             3279                      "Dixon Mills"       5
22             3213                   "Van Vorst Park"       6
23             3266        "Kiosk in a box Deployment"       6
24             3186                    "Grove St PATH"       6
25             3183                   "Exchange Place"       9
26             3040                "SSP Tech Workshop"       9
27             3036                        "8D OPS 01"      10
28             3214                 "Essex Light Rail"      16
29             3184                      "Paulus Hook"      17
..              ...                                ...     ...
659             462                 "W 22 St & 10 Ave"  181016
660             446                  "W 24 St & 7 Ave"  182413
661            3002       "South End Ave & Liberty St"  186950
662            2006           "Central Park S & 6 Ave"  187608
663             387          "Centre St & Chambers St"  188657
664             127            "Barrow St & Hudson St"  190352
665             523                  "W 38 St & 8 Ave"  192067
666             379                  "W 31 St & 7 Ave"  196884
667             514                 "12 Ave & W 40 St"  201171
668             492                  "W 33 St & 7 Ave"  203789
669             168                  "W 18 St & 6 Ave"  211045
670             499               "Broadway & W 60 St"  211577
671             327         "Vesey Pl & River Terrace"  214609
672             358    "Christopher St & Greenwich St"  218719
673             444               "Broadway & W 24 St"  226128
674             490                  "8 Ave & W 33 St"  227732
675             382          "University Pl & E 14 St"  228597
676             521                  "8 Ave & W 31 St"  231151
677             368               "Carmine St & 6 Ave"  235130
678             459                 "W 20 St & 11 Ave"  237703
679             477                  "W 41 St & 8 Ave"  240469
680             284            "Greenwich Ave & 8 Ave"  246466
681             151         "Cleveland Pl & Spring St"  249596
682             285               "Broadway & E 14 St"  266106
683             402               "Broadway & E 22 St"  269308
684             293            "Lafayette St & E 8 St"  278215
685             426            "West St & Chambers St"  288822
686             435                  "W 21 St & 6 Ave"  302711
687             497               "E 17 St & Broadway"  332182
688             519            "Pershing Square North"  359122

[689 rows x 3 columns]

In [54]:
d0 = df1.toPandas().set_index('start_station_id')
d0[(d0.lon!=0.) | (d0.lat!=0.)]

KeyError: 'start_station_id'

In [38]:
df1 = spark.sql('''SELECT start_station_id, start_station_latitude, 
                          start_station_longitude
                     from parquet.`/data/citibike.parquet`
                     where start_station_id=3385
                     ''')

In [40]:
df1.count()

1

In [ ]:
df2.toPandas()

In [12]:
df = spark.read.load('/data/subway.parquet')
# df = df.repartition(662, "start_station_id")
# df = df.sortWithinPartitions("start_time")
# df.write.parquet('/data/citibike_partitioned.parquet', 
# #                  partitionBy=['start_station_id'], 
#                  mode='overwrite', compression="snappy")

In [36]:
spark.sql('SELECT count(distinct(unit)) from parquet.`/data/subway.parquet`').show()

Py4JJavaError: An error occurred while calling o510.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 69.0 failed 1 times, most recent failure: Lost task 2.0 in stage 69.0 (TID 3231, localhost): java.lang.ArrayIndexOutOfBoundsException

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1442)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1441)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1441)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1667)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1622)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1611)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1873)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1886)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1899)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:347)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:39)
	at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2193)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
	at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2546)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2192)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2199)
	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:1935)
	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:1934)
	at org.apache.spark.sql.Dataset.withTypedCallback(Dataset.scala:2576)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:1934)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2149)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:237)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException

In [1]:
%matplotlib inline

In [2]:
import dask.dataframe as dd
import pandas as pd
import numpy as np
import geopandas
from shapely.geometry import Point
from matplotlib import pyplot as plt

In [3]:
df_in = dd.read_parquet('/data/green.parquet')

In [4]:
df_in = df_in.reset_index()

In [41]:
def spatial_join(df, lon_var, lat_var, locid_var):
    localdf = df[[lon_var, lat_var, locid_var]].copy()
    localdf[lon_var] = localdf[lon_var].fillna(value=0.)
    localdf[lat_var] = localdf[lat_var].fillna(value=0.)
    localdf['replace_locid'] = localdf[locid_var].isnull() & (localdf[lon_var] != 0.) & (localdf[lat_var] != 0.)
    
    if (np.any(localdf['replace_locid'])):
        shape_df = geopandas.read_file('../shapefiles/taxi_zones_latlon.shp')
        shape_df.drop(['OBJECTID', "Shape_Area", "Shape_Leng", "borough", "zone"],
                  axis=1, inplace=True)
        
        try:
            local_gdf = geopandas.GeoDataFrame(
                localdf, crs={'init': 'epsg:4326'}, 
                geometry=[Point(xy) for xy in 
                          zip(localdf[lon_var], localdf[lat_var])])
            local_gdf = geopandas.sjoin(local_gdf, shape_df, how='left', op='intersects')

            # restore values we do not want to replace
            local_gdf.LocationID.values[~local_gdf.replace_locid] = ((local_gdf[locid_var])[~local_gdf.replace_locid]).values
            return local_gdf.LocationID.rename(locid_var)
        except ValueError as ve:
            print(ve)
            return df[locid_var]
        
    else:
        return df[locid_var]


    

#     if np.any((lats[locs_to_replace] != 0.) | (lons[locs_to_replace] != 0.)):
#         points = [Point(xy) for xy in zip(lons, lats)]
#         points_df = geopandas.GeoDataFrame(
#             crs={'init': 'epsg:4326'}, geometry=points)
#         try:
#             joined = geopandas.sjoin(points_df, shape_df, op='intersects')
#             joined = joined.drop(['geometry', 'index_right'], axis=1)
            
#             # this seems like it could be done better
            
#             dflocal = (df[[locid_var, ]]).copy(True)
#             dflocal = dflocal.merge(joined, how='left', left_index=True,
#                                     right_index=True)
            
#             return dflocal.LocationID.rename(locid_var)
#         except ValueError as ve:
#             # this error occurs when there are no rows in joined due to
#             # no points having coordinates. Skip.
#             return df[locid_var]
#         except Exception as e:
#             print(e)
#             return df[locid_var]
#     else:
#         return df[locid_var]

In [42]:
spatial_join(df_in.get_partition(0), "dropoff_longitude", "dropoff_latitude",
    "dropoff_location_id")

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
5         NaN
6         NaN
7       146.0
8       146.0
9         NaN
10        NaN
11        NaN
12        NaN
13        NaN
14        NaN
15        NaN
16        NaN
17        NaN
18        NaN
19        NaN
20        NaN
21        NaN
22        NaN
23        NaN
24        NaN
25        NaN
26        NaN
27        NaN
28        NaN
29        NaN
        ...
7593    226.0
7594     37.0
7595    135.0
7596    189.0
7597    241.0
7598    162.0
7599    249.0
7600    161.0
7601    239.0
7602    134.0
7603     56.0
7604    148.0
7605    158.0
7606    197.0
7607      7.0
7608    198.0
7609    112.0
7610    106.0
7611    263.0
7612    232.0
7613    129.0
7614    151.0
7615    134.0
7616      7.0
7617     83.0
7618     74.0
7619     95.0
7620    249.0
7621     41.0
7622     89.0
Name: dropoff_location_id, dtype: float64

In [69]:
df_in['dropoff_location_id'] = df_in.map_partitions(
    spatial_join, "dropoff_longitude", "dropoff_latitude",
    "dropoff_location_id", meta=('dropoff_location_id', np.float64))
df_in['pickup_location_id'] = df_in.map_partitions(
    spatial_join, "pickup_longitude", "pickup_latitude",
    "pickup_location_id", meta=('pickup_location_id', np.float64))

In [ ]:
df_in.to_parquet('/data/newgreen.parquet',
        compression="SNAPPY",
        has_nulls=True,
        object_encoding='json'                )

(329411,)
(343445,)
(408311,)
(408265,)
(329411,)
(343445,)
(408311,)
(408265,)

In [43]:
shape_df = geopandas.read_file('../shapefiles/taxi_zones_latlon.shp')

In [45]:
shape_df.LocationID.count()

263